# Generated by Django 5.1.3 on 2024-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Viewer', 'Viewer'), ('Moderator', 'Moderator')], default='Viewer', max_length=20),
        ),
    ]
