# Generated by Django 5.1.3 on 2024-11-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
